### ISSUE TITLE
Post-load hook to support Ignite json config

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/gluegun#196]
Per [this comment](https://github.com/infinitered/ignite/commit/e539b12b9cb4e986ed6ad84d5047baf86e6457ff#diff-9b650c036a56768626632ea00c79b912R30), Gluegun needs to be updated to provide a post-load hook so we don't need a toml file in our Ignite plugins. This issue is set to track progress on that.

> Note! This will be replaced shortly with `ignite.json`.  I just need to patch up gluegun to provide a post-load hook so ignite can do this.

**Comment by skellock** [comment]
Thanks.  Forgot about this entirely.

Currently we are only [loading toml](https://github.com/infinitered/gluegun/blob/master/packages/gluegun/src/loaders/toml-plugin-loader.js#L99). We could also try loading a similar json file from the same place.

A shallow merge of the two into a config object would do just fine because I doubt you'd have both.

Then rename the file to plugin-loader.

**Comment by skellock** [comment]
Replaced by #229
