### ISSUE TITLE
[Docs?] system.run is an async function but strings.trim is sync

### ISSUE THREAD

**Issue by sw-yx** [infinitered/gluegun#459]
The docs have this bit of code: https://infinitered.github.io/gluegun/#/?id=quick-start

```
    const awesome = strings.trim(system.run('whoami'))
```

which typescript catches as invalid:

![image](https://user-images.githubusercontent.com/6764957/52912269-3e469c00-3253-11e9-8dc5-c2f563cdb729.png)

is the docs out of date?

**Comment by jamonholmgren** [comment]
@sw-yx Yessir, out of date docs. We need an `await` in there! I'll mark this as a beginner issue.

```js
const awesome = strings.trim(await system.run('whoami'))
```

**Comment by akintoluvic** [comment]
I'd like to take this issue. I'll look for the documentation, but it would be helpful if you can point me to the right file.

**Comment by jamonholmgren** [comment]
@akintoluvic Cool! So, in this case, it's actually in two places:

The [readme.md](https://github.com/infinitered/gluegun/blob/master/readme.md)

and the other [readme](https://github.com/infinitered/gluegun/blob/master/docs/README.md)

Unfortunately, because of the [documentation website]( https://infinitered.github.io/gluegun/), we have to have two copies of the readme file.

So, what I would do is edit the main one (the first one) and then copy & paste it entirely into the second one in ./docs. That way they stay identical.

**Comment by jamonholmgren** [comment]
Additionally, take a look at the [contributing guide](https://github.com/infinitered/gluegun/blob/master/docs/contributing.md) which might help you get started.
